site_name: 绿巨人视频下载汅app福引导免费大全
site_author: 绿巨人视频
site_description: 绿巨人视频的安装方法 经典怀旧中文单机,一次下载,长期可用,售后一对一包安装,绿巨人2008的安装方法 免费更新,免费疑问解答!
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
